// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inflion.proto

package inflionserverpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunFlowResponse_ExitStatus int32

const (
	RunFlowResponse_SUCCESS RunFlowResponse_ExitStatus = 0
	RunFlowResponse_FAILURE RunFlowResponse_ExitStatus = 1
)

var RunFlowResponse_ExitStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var RunFlowResponse_ExitStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x RunFlowResponse_ExitStatus) String() string {
	return proto.EnumName(RunFlowResponse_ExitStatus_name, int32(x))
}

func (RunFlowResponse_ExitStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{1, 0}
}

type RunFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunFlowRequest) Reset()         { *m = RunFlowRequest{} }
func (m *RunFlowRequest) String() string { return proto.CompactTextString(m) }
func (*RunFlowRequest) ProtoMessage()    {}
func (*RunFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{0}
}

func (m *RunFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunFlowRequest.Unmarshal(m, b)
}
func (m *RunFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunFlowRequest.Marshal(b, m, deterministic)
}
func (m *RunFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunFlowRequest.Merge(m, src)
}
func (m *RunFlowRequest) XXX_Size() int {
	return xxx_messageInfo_RunFlowRequest.Size(m)
}
func (m *RunFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunFlowRequest proto.InternalMessageInfo

func (m *RunFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RunFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RunFlowResponse struct {
	Status               RunFlowResponse_ExitStatus `protobuf:"varint,1,opt,name=status,proto3,enum=inflionserverpb.RunFlowResponse_ExitStatus" json:"status,omitempty"`
	Output               string                     `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RunFlowResponse) Reset()         { *m = RunFlowResponse{} }
func (m *RunFlowResponse) String() string { return proto.CompactTextString(m) }
func (*RunFlowResponse) ProtoMessage()    {}
func (*RunFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{1}
}

func (m *RunFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunFlowResponse.Unmarshal(m, b)
}
func (m *RunFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunFlowResponse.Marshal(b, m, deterministic)
}
func (m *RunFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunFlowResponse.Merge(m, src)
}
func (m *RunFlowResponse) XXX_Size() int {
	return xxx_messageInfo_RunFlowResponse.Size(m)
}
func (m *RunFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunFlowResponse proto.InternalMessageInfo

func (m *RunFlowResponse) GetStatus() RunFlowResponse_ExitStatus {
	if m != nil {
		return m.Status
	}
	return RunFlowResponse_SUCCESS
}

func (m *RunFlowResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type CreateFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFlowRequest) Reset()         { *m = CreateFlowRequest{} }
func (m *CreateFlowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFlowRequest) ProtoMessage()    {}
func (*CreateFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{2}
}

func (m *CreateFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFlowRequest.Unmarshal(m, b)
}
func (m *CreateFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFlowRequest.Marshal(b, m, deterministic)
}
func (m *CreateFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFlowRequest.Merge(m, src)
}
func (m *CreateFlowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFlowRequest.Size(m)
}
func (m *CreateFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFlowRequest proto.InternalMessageInfo

func (m *CreateFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateFlowRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFlowResponse) Reset()         { *m = CreateFlowResponse{} }
func (m *CreateFlowResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFlowResponse) ProtoMessage()    {}
func (*CreateFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{3}
}

func (m *CreateFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFlowResponse.Unmarshal(m, b)
}
func (m *CreateFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFlowResponse.Marshal(b, m, deterministic)
}
func (m *CreateFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFlowResponse.Merge(m, src)
}
func (m *CreateFlowResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFlowResponse.Size(m)
}
func (m *CreateFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFlowResponse proto.InternalMessageInfo

func (m *CreateFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlowRequest) Reset()         { *m = GetFlowRequest{} }
func (m *GetFlowRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlowRequest) ProtoMessage()    {}
func (*GetFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{4}
}

func (m *GetFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlowRequest.Unmarshal(m, b)
}
func (m *GetFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlowRequest.Marshal(b, m, deterministic)
}
func (m *GetFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlowRequest.Merge(m, src)
}
func (m *GetFlowRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlowRequest.Size(m)
}
func (m *GetFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlowRequest proto.InternalMessageInfo

func (m *GetFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *GetFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlowResponse) Reset()         { *m = GetFlowResponse{} }
func (m *GetFlowResponse) String() string { return proto.CompactTextString(m) }
func (*GetFlowResponse) ProtoMessage()    {}
func (*GetFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{5}
}

func (m *GetFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlowResponse.Unmarshal(m, b)
}
func (m *GetFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlowResponse.Marshal(b, m, deterministic)
}
func (m *GetFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlowResponse.Merge(m, src)
}
func (m *GetFlowResponse) XXX_Size() int {
	return xxx_messageInfo_GetFlowResponse.Size(m)
}
func (m *GetFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlowResponse proto.InternalMessageInfo

func (m *GetFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetFlowResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFlowRequest) Reset()         { *m = UpdateFlowRequest{} }
func (m *UpdateFlowRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFlowRequest) ProtoMessage()    {}
func (*UpdateFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{6}
}

func (m *UpdateFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFlowRequest.Unmarshal(m, b)
}
func (m *UpdateFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFlowRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFlowRequest.Merge(m, src)
}
func (m *UpdateFlowRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFlowRequest.Size(m)
}
func (m *UpdateFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFlowRequest proto.InternalMessageInfo

func (m *UpdateFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *UpdateFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateFlowRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFlowResponse) Reset()         { *m = UpdateFlowResponse{} }
func (m *UpdateFlowResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFlowResponse) ProtoMessage()    {}
func (*UpdateFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{7}
}

func (m *UpdateFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFlowResponse.Unmarshal(m, b)
}
func (m *UpdateFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFlowResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFlowResponse.Merge(m, src)
}
func (m *UpdateFlowResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFlowResponse.Size(m)
}
func (m *UpdateFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFlowResponse proto.InternalMessageInfo

func (m *UpdateFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFlowRequest) Reset()         { *m = DeleteFlowRequest{} }
func (m *DeleteFlowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFlowRequest) ProtoMessage()    {}
func (*DeleteFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{8}
}

func (m *DeleteFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFlowRequest.Unmarshal(m, b)
}
func (m *DeleteFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFlowRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFlowRequest.Merge(m, src)
}
func (m *DeleteFlowRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFlowRequest.Size(m)
}
func (m *DeleteFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFlowRequest proto.InternalMessageInfo

func (m *DeleteFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *DeleteFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFlowResponse) Reset()         { *m = DeleteFlowResponse{} }
func (m *DeleteFlowResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFlowResponse) ProtoMessage()    {}
func (*DeleteFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{9}
}

func (m *DeleteFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFlowResponse.Unmarshal(m, b)
}
func (m *DeleteFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFlowResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFlowResponse.Merge(m, src)
}
func (m *DeleteFlowResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFlowResponse.Size(m)
}
func (m *DeleteFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFlowResponse proto.InternalMessageInfo

func (m *DeleteFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateRuleRequest struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleRequest) Reset()         { *m = CreateRuleRequest{} }
func (m *CreateRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuleRequest) ProtoMessage()    {}
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{10}
}

func (m *CreateRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleRequest.Unmarshal(m, b)
}
func (m *CreateRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleRequest.Merge(m, src)
}
func (m *CreateRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuleRequest.Size(m)
}
func (m *CreateRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleRequest proto.InternalMessageInfo

func (m *CreateRuleRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateRuleResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleResponse) Reset()         { *m = CreateRuleResponse{} }
func (m *CreateRuleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuleResponse) ProtoMessage()    {}
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{11}
}

func (m *CreateRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleResponse.Unmarshal(m, b)
}
func (m *CreateRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleResponse.Merge(m, src)
}
func (m *CreateRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuleResponse.Size(m)
}
func (m *CreateRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleResponse proto.InternalMessageInfo

func (m *CreateRuleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetRuleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRuleRequest) Reset()         { *m = GetRuleRequest{} }
func (m *GetRuleRequest) String() string { return proto.CompactTextString(m) }
func (*GetRuleRequest) ProtoMessage()    {}
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{12}
}

func (m *GetRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleRequest.Unmarshal(m, b)
}
func (m *GetRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleRequest.Marshal(b, m, deterministic)
}
func (m *GetRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleRequest.Merge(m, src)
}
func (m *GetRuleRequest) XXX_Size() int {
	return xxx_messageInfo_GetRuleRequest.Size(m)
}
func (m *GetRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleRequest proto.InternalMessageInfo

func (m *GetRuleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetRuleResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRuleResponse) Reset()         { *m = GetRuleResponse{} }
func (m *GetRuleResponse) String() string { return proto.CompactTextString(m) }
func (*GetRuleResponse) ProtoMessage()    {}
func (*GetRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{13}
}

func (m *GetRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleResponse.Unmarshal(m, b)
}
func (m *GetRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleResponse.Marshal(b, m, deterministic)
}
func (m *GetRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleResponse.Merge(m, src)
}
func (m *GetRuleResponse) XXX_Size() int {
	return xxx_messageInfo_GetRuleResponse.Size(m)
}
func (m *GetRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleResponse proto.InternalMessageInfo

func (m *GetRuleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetRuleResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateRuleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRuleRequest) Reset()         { *m = UpdateRuleRequest{} }
func (m *UpdateRuleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRuleRequest) ProtoMessage()    {}
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{14}
}

func (m *UpdateRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRuleRequest.Unmarshal(m, b)
}
func (m *UpdateRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRuleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRuleRequest.Merge(m, src)
}
func (m *UpdateRuleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRuleRequest.Size(m)
}
func (m *UpdateRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRuleRequest proto.InternalMessageInfo

func (m *UpdateRuleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRuleRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateRuleResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRuleResponse) Reset()         { *m = UpdateRuleResponse{} }
func (m *UpdateRuleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRuleResponse) ProtoMessage()    {}
func (*UpdateRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{15}
}

func (m *UpdateRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRuleResponse.Unmarshal(m, b)
}
func (m *UpdateRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRuleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRuleResponse.Merge(m, src)
}
func (m *UpdateRuleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRuleResponse.Size(m)
}
func (m *UpdateRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRuleResponse proto.InternalMessageInfo

func (m *UpdateRuleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRuleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuleRequest) Reset()         { *m = DeleteRuleRequest{} }
func (m *DeleteRuleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRuleRequest) ProtoMessage()    {}
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{16}
}

func (m *DeleteRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleRequest.Unmarshal(m, b)
}
func (m *DeleteRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleRequest.Merge(m, src)
}
func (m *DeleteRuleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleRequest.Size(m)
}
func (m *DeleteRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleRequest proto.InternalMessageInfo

func (m *DeleteRuleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRuleResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuleResponse) Reset()         { *m = DeleteRuleResponse{} }
func (m *DeleteRuleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRuleResponse) ProtoMessage()    {}
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{17}
}

func (m *DeleteRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleResponse.Unmarshal(m, b)
}
func (m *DeleteRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleResponse.Merge(m, src)
}
func (m *DeleteRuleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleResponse.Size(m)
}
func (m *DeleteRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleResponse proto.InternalMessageInfo

func (m *DeleteRuleResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	FlowId               string   `protobuf:"bytes,3,opt,name=flowId,proto3" json:"flowId,omitempty"`
	Schedule             string   `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{18}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateJobRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *CreateJobRequest) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

type CreateJobResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{19}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobRequest) Reset()         { *m = RemoveJobRequest{} }
func (m *RemoveJobRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveJobRequest) ProtoMessage()    {}
func (*RemoveJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{20}
}

func (m *RemoveJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobRequest.Unmarshal(m, b)
}
func (m *RemoveJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobRequest.Marshal(b, m, deterministic)
}
func (m *RemoveJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobRequest.Merge(m, src)
}
func (m *RemoveJobRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveJobRequest.Size(m)
}
func (m *RemoveJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobRequest proto.InternalMessageInfo

func (m *RemoveJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoveJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type RemoveJobResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobResponse) Reset()         { *m = RemoveJobResponse{} }
func (m *RemoveJobResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveJobResponse) ProtoMessage()    {}
func (*RemoveJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f383caa5366d091, []int{21}
}

func (m *RemoveJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobResponse.Unmarshal(m, b)
}
func (m *RemoveJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobResponse.Marshal(b, m, deterministic)
}
func (m *RemoveJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobResponse.Merge(m, src)
}
func (m *RemoveJobResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveJobResponse.Size(m)
}
func (m *RemoveJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobResponse proto.InternalMessageInfo

func (m *RemoveJobResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("inflionserverpb.RunFlowResponse_ExitStatus", RunFlowResponse_ExitStatus_name, RunFlowResponse_ExitStatus_value)
	proto.RegisterType((*RunFlowRequest)(nil), "inflionserverpb.RunFlowRequest")
	proto.RegisterType((*RunFlowResponse)(nil), "inflionserverpb.RunFlowResponse")
	proto.RegisterType((*CreateFlowRequest)(nil), "inflionserverpb.CreateFlowRequest")
	proto.RegisterType((*CreateFlowResponse)(nil), "inflionserverpb.CreateFlowResponse")
	proto.RegisterType((*GetFlowRequest)(nil), "inflionserverpb.GetFlowRequest")
	proto.RegisterType((*GetFlowResponse)(nil), "inflionserverpb.GetFlowResponse")
	proto.RegisterType((*UpdateFlowRequest)(nil), "inflionserverpb.UpdateFlowRequest")
	proto.RegisterType((*UpdateFlowResponse)(nil), "inflionserverpb.UpdateFlowResponse")
	proto.RegisterType((*DeleteFlowRequest)(nil), "inflionserverpb.DeleteFlowRequest")
	proto.RegisterType((*DeleteFlowResponse)(nil), "inflionserverpb.DeleteFlowResponse")
	proto.RegisterType((*CreateRuleRequest)(nil), "inflionserverpb.CreateRuleRequest")
	proto.RegisterType((*CreateRuleResponse)(nil), "inflionserverpb.CreateRuleResponse")
	proto.RegisterType((*GetRuleRequest)(nil), "inflionserverpb.GetRuleRequest")
	proto.RegisterType((*GetRuleResponse)(nil), "inflionserverpb.GetRuleResponse")
	proto.RegisterType((*UpdateRuleRequest)(nil), "inflionserverpb.UpdateRuleRequest")
	proto.RegisterType((*UpdateRuleResponse)(nil), "inflionserverpb.UpdateRuleResponse")
	proto.RegisterType((*DeleteRuleRequest)(nil), "inflionserverpb.DeleteRuleRequest")
	proto.RegisterType((*DeleteRuleResponse)(nil), "inflionserverpb.DeleteRuleResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "inflionserverpb.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "inflionserverpb.CreateJobResponse")
	proto.RegisterType((*RemoveJobRequest)(nil), "inflionserverpb.RemoveJobRequest")
	proto.RegisterType((*RemoveJobResponse)(nil), "inflionserverpb.RemoveJobResponse")
}

func init() {
	proto.RegisterFile("inflion.proto", fileDescriptor_7f383caa5366d091)
}

var fileDescriptor_7f383caa5366d091 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0x3f, 0x27, 0xf9, 0xdc, 0xf6, 0x42, 0xd3, 0x64, 0x40, 0x25, 0xb2, 0x90, 0x08, 0x53,
	0x04, 0xa8, 0x48, 0x89, 0x08, 0x42, 0x48, 0x15, 0x2c, 0xaa, 0xd0, 0x56, 0xad, 0xd8, 0xe0, 0xa8,
	0x4b, 0x16, 0x76, 0x3d, 0x0d, 0xae, 0x8c, 0xc7, 0xd8, 0xe3, 0x14, 0x96, 0xf0, 0x0a, 0x48, 0x2c,
	0x79, 0x27, 0xc4, 0x2b, 0xf0, 0x20, 0x68, 0xc6, 0x7f, 0x3a, 0xb6, 0xc7, 0x4e, 0x94, 0x1d, 0x43,
	0xe6, 0x9e, 0xdf, 0xbd, 0xf7, 0x8c, 0x8f, 0x0a, 0xdb, 0xae, 0x7f, 0xe9, 0xb9, 0xd4, 0x1f, 0x05,
	0x21, 0x65, 0x14, 0xed, 0xa4, 0xc7, 0x88, 0x84, 0x0b, 0x12, 0x06, 0xb6, 0x71, 0x7f, 0x4e, 0xe9,
	0xdc, 0x23, 0x63, 0x2b, 0x70, 0xc7, 0x96, 0xef, 0x53, 0x66, 0x31, 0xfe, 0x73, 0x72, 0x1d, 0x1f,
	0x40, 0xd7, 0x8c, 0xfd, 0x63, 0x8f, 0x5e, 0x9b, 0xe4, 0x73, 0x4c, 0x22, 0x86, 0x06, 0xb0, 0x11,
	0x84, 0xf4, 0x8a, 0x5c, 0xb0, 0x81, 0x36, 0xd4, 0x9e, 0x6e, 0x99, 0xd9, 0x11, 0x75, 0xa1, 0xe5,
	0x3a, 0x83, 0x96, 0xf8, 0xcf, 0x96, 0xeb, 0xe0, 0x9f, 0x1a, 0xec, 0xe4, 0xc5, 0x51, 0xc0, 0x99,
	0x68, 0x0a, 0x7a, 0xc4, 0x2c, 0x16, 0x47, 0xa2, 0xb8, 0x3b, 0x79, 0x36, 0x2a, 0xf5, 0x33, 0x2a,
	0x55, 0x8c, 0x8e, 0xbe, 0xb8, 0x6c, 0x26, 0x4a, 0xcc, 0xb4, 0x14, 0xed, 0x82, 0x4e, 0x63, 0x16,
	0xc4, 0x2c, 0x85, 0xa5, 0x27, 0xfc, 0x18, 0xe0, 0xe6, 0x36, 0xba, 0x05, 0x1b, 0xb3, 0xf3, 0xe9,
	0xf4, 0x68, 0x36, 0xeb, 0xfd, 0xc7, 0x0f, 0xc7, 0x87, 0xa7, 0xef, 0xce, 0xcd, 0xa3, 0x9e, 0x86,
	0x0f, 0xa1, 0x3f, 0x0d, 0x89, 0xc5, 0xc8, 0x6a, 0x73, 0x21, 0xe8, 0xd8, 0xd4, 0xf9, 0x9a, 0xc2,
	0xc4, 0xbf, 0xf1, 0x23, 0x40, 0xb2, 0x44, 0x3a, 0x5d, 0xb2, 0x01, 0x2d, 0xdf, 0xc0, 0x01, 0x74,
	0x4f, 0x08, 0x5b, 0x6f, 0x7b, 0x2f, 0x61, 0x27, 0xaf, 0x55, 0xcb, 0x2b, 0x1b, 0x7b, 0x0f, 0xfd,
	0xf3, 0xc0, 0x59, 0x79, 0xb6, 0x12, 0x35, 0x97, 0x6c, 0x17, 0x67, 0x95, 0x25, 0x6b, 0x66, 0x7d,
	0x03, 0xfd, 0xb7, 0xc4, 0x23, 0x6b, 0x82, 0x39, 0x44, 0x2e, 0xaf, 0x81, 0x3c, 0xc9, 0x9c, 0x33,
	0x63, 0x8f, 0x64, 0x90, 0xac, 0x67, 0x4d, 0xe5, 0x4f, 0x72, 0xb1, 0x46, 0x6e, 0x28, 0xfc, 0x91,
	0xb5, 0xca, 0x37, 0x12, 0x17, 0x9a, 0x44, 0x94, 0x2e, 0xbc, 0xca, 0x5c, 0x68, 0xd0, 0xae, 0x7b,
	0x57, 0x72, 0x61, 0x4d, 0xdf, 0x7b, 0xd9, 0xae, 0x9b, 0x5a, 0xcf, 0x37, 0xda, 0x28, 0x15, 0x40,
	0x2f, 0x59, 0xd4, 0x19, 0xb5, 0xab, 0x4a, 0xff, 0x8b, 0x46, 0x25, 0x17, 0x5b, 0x45, 0x17, 0x77,
	0x41, 0xbf, 0xf4, 0xe8, 0xf5, 0xa9, 0x93, 0x3e, 0x98, 0xf4, 0x84, 0x0c, 0xd8, 0x8c, 0x2e, 0x3e,
	0x12, 0x27, 0xf6, 0xc8, 0xa0, 0x23, 0x7e, 0xc9, 0xcf, 0xbc, 0x79, 0x89, 0x58, 0xd3, 0xd6, 0x6b,
	0xe8, 0x99, 0xe4, 0x13, 0x5d, 0xac, 0xd5, 0x16, 0x47, 0x48, 0xd5, 0x15, 0x84, 0x28, 0x9f, 0x7c,
	0xeb, 0x40, 0x87, 0x3f, 0x36, 0x64, 0x41, 0xdb, 0x8c, 0x7d, 0xf4, 0xa0, 0x3e, 0x8a, 0x04, 0xdf,
	0x18, 0x2e, 0xcb, 0x2a, 0x7c, 0xef, 0xfb, 0x9f, 0xbf, 0x3f, 0x5a, 0x7d, 0x7c, 0x7b, 0xbc, 0x78,
	0x3e, 0xe6, 0xab, 0x18, 0x87, 0xb1, 0x7f, 0xa0, 0xed, 0xa3, 0x39, 0xe8, 0xc9, 0xcc, 0x08, 0x57,
	0x44, 0x2a, 0x51, 0x64, 0xec, 0x35, 0xde, 0x49, 0x59, 0x77, 0x05, 0xab, 0x8b, 0xb7, 0x32, 0x56,
	0xc4, 0x41, 0x1f, 0xa0, 0x7d, 0x42, 0x98, 0x62, 0x96, 0x62, 0x0e, 0x29, 0x66, 0x29, 0x85, 0x0d,
	0xbe, 0x23, 0xf4, 0xb7, 0xd1, 0x66, 0xa6, 0xcf, 0xe5, 0x2f, 0x41, 0x4f, 0x9e, 0xa7, 0x62, 0x8e,
	0x4a, 0xec, 0x28, 0xe6, 0xa8, 0xe6, 0x48, 0xc6, 0x31, 0xca, 0x9c, 0xe4, 0xed, 0x2a, 0x38, 0x95,
	0x94, 0x51, 0x70, 0xaa, 0x51, 0x92, 0x71, 0xf6, 0x65, 0xce, 0xe4, 0x57, 0x1b, 0x3a, 0xfc, 0xf3,
	0x58, 0xc1, 0x20, 0xe9, 0x53, 0xab, 0x35, 0x48, 0xfe, 0xd2, 0x8a, 0x06, 0x85, 0xb1, 0x47, 0x96,
	0x1a, 0x24, 0x23, 0x86, 0xf5, 0x17, 0x54, 0x06, 0x71, 0xfd, 0xd5, 0x0c, 0x6a, 0x9e, 0xa3, 0x1a,
	0x3e, 0x45, 0x83, 0x24, 0xce, 0x12, 0x83, 0x9a, 0x39, 0xd5, 0x64, 0x2a, 0x1a, 0x94, 0x72, 0x26,
	0xbf, 0x35, 0x68, 0x9f, 0x51, 0x1b, 0x39, 0xb9, 0x3f, 0x0f, 0x6b, 0x76, 0x7f, 0x13, 0x14, 0x06,
	0x6e, 0xba, 0x52, 0xa4, 0x61, 0x41, 0xbb, 0xa2, 0xb6, 0x30, 0xc7, 0x01, 0x3d, 0xc9, 0x0d, 0x05,
	0xa5, 0x1c, 0x47, 0x0a, 0x4a, 0x25, 0x73, 0x8a, 0x33, 0xa5, 0x14, 0x5b, 0x17, 0x7f, 0x5a, 0xbd,
	0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xc7, 0xd9, 0x2c, 0x9a, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FlowClient is the client API for Flow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlowClient interface {
	Run(ctx context.Context, in *RunFlowRequest, opts ...grpc.CallOption) (*RunFlowResponse, error)
	Create(ctx context.Context, in *CreateFlowRequest, opts ...grpc.CallOption) (*CreateFlowResponse, error)
	Get(ctx context.Context, in *GetFlowRequest, opts ...grpc.CallOption) (*GetFlowResponse, error)
	Update(ctx context.Context, in *UpdateFlowRequest, opts ...grpc.CallOption) (*UpdateFlowResponse, error)
	Delete(ctx context.Context, in *DeleteFlowRequest, opts ...grpc.CallOption) (*DeleteFlowResponse, error)
}

type flowClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowClient(cc grpc.ClientConnInterface) FlowClient {
	return &flowClient{cc}
}

func (c *flowClient) Run(ctx context.Context, in *RunFlowRequest, opts ...grpc.CallOption) (*RunFlowResponse, error) {
	out := new(RunFlowResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Flow/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowClient) Create(ctx context.Context, in *CreateFlowRequest, opts ...grpc.CallOption) (*CreateFlowResponse, error) {
	out := new(CreateFlowResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Flow/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowClient) Get(ctx context.Context, in *GetFlowRequest, opts ...grpc.CallOption) (*GetFlowResponse, error) {
	out := new(GetFlowResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Flow/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowClient) Update(ctx context.Context, in *UpdateFlowRequest, opts ...grpc.CallOption) (*UpdateFlowResponse, error) {
	out := new(UpdateFlowResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Flow/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowClient) Delete(ctx context.Context, in *DeleteFlowRequest, opts ...grpc.CallOption) (*DeleteFlowResponse, error) {
	out := new(DeleteFlowResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Flow/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowServer is the server API for Flow service.
type FlowServer interface {
	Run(context.Context, *RunFlowRequest) (*RunFlowResponse, error)
	Create(context.Context, *CreateFlowRequest) (*CreateFlowResponse, error)
	Get(context.Context, *GetFlowRequest) (*GetFlowResponse, error)
	Update(context.Context, *UpdateFlowRequest) (*UpdateFlowResponse, error)
	Delete(context.Context, *DeleteFlowRequest) (*DeleteFlowResponse, error)
}

// UnimplementedFlowServer can be embedded to have forward compatible implementations.
type UnimplementedFlowServer struct {
}

func (*UnimplementedFlowServer) Run(ctx context.Context, req *RunFlowRequest) (*RunFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (*UnimplementedFlowServer) Create(ctx context.Context, req *CreateFlowRequest) (*CreateFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedFlowServer) Get(ctx context.Context, req *GetFlowRequest) (*GetFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedFlowServer) Update(ctx context.Context, req *UpdateFlowRequest) (*UpdateFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedFlowServer) Delete(ctx context.Context, req *DeleteFlowRequest) (*DeleteFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterFlowServer(s *grpc.Server, srv FlowServer) {
	s.RegisterService(&_Flow_serviceDesc, srv)
}

func _Flow_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Flow/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServer).Run(ctx, req.(*RunFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flow_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Flow/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServer).Create(ctx, req.(*CreateFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flow_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Flow/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServer).Get(ctx, req.(*GetFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flow_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Flow/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServer).Update(ctx, req.(*UpdateFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flow_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Flow/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServer).Delete(ctx, req.(*DeleteFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Flow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inflionserverpb.Flow",
	HandlerType: (*FlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Flow_Run_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Flow_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Flow_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Flow_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Flow_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inflion.proto",
}

// RuleClient is the client API for Rule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuleClient interface {
	Create(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error)
	Get(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error)
	Update(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*UpdateRuleResponse, error)
	Delete(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error)
}

type ruleClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleClient(cc grpc.ClientConnInterface) RuleClient {
	return &ruleClient{cc}
}

func (c *ruleClient) Create(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error) {
	out := new(CreateRuleResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Rule/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) Get(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error) {
	out := new(GetRuleResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Rule/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) Update(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*UpdateRuleResponse, error) {
	out := new(UpdateRuleResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Rule/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) Delete(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error) {
	out := new(DeleteRuleResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Rule/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleServer is the server API for Rule service.
type RuleServer interface {
	Create(context.Context, *CreateRuleRequest) (*CreateRuleResponse, error)
	Get(context.Context, *GetRuleRequest) (*GetRuleResponse, error)
	Update(context.Context, *UpdateRuleRequest) (*UpdateRuleResponse, error)
	Delete(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
}

// UnimplementedRuleServer can be embedded to have forward compatible implementations.
type UnimplementedRuleServer struct {
}

func (*UnimplementedRuleServer) Create(ctx context.Context, req *CreateRuleRequest) (*CreateRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedRuleServer) Get(ctx context.Context, req *GetRuleRequest) (*GetRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedRuleServer) Update(ctx context.Context, req *UpdateRuleRequest) (*UpdateRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedRuleServer) Delete(ctx context.Context, req *DeleteRuleRequest) (*DeleteRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterRuleServer(s *grpc.Server, srv RuleServer) {
	s.RegisterService(&_Rule_serviceDesc, srv)
}

func _Rule_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Rule/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).Create(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Rule/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).Get(ctx, req.(*GetRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Rule/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).Update(ctx, req.(*UpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Rule/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).Delete(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rule_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inflionserverpb.Rule",
	HandlerType: (*RuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Rule_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Rule_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Rule_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Rule_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inflion.proto",
}

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error)
}

type jobClient struct {
	cc grpc.ClientConnInterface
}

func NewJobClient(cc grpc.ClientConnInterface) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Job/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error) {
	out := new(RemoveJobResponse)
	err := c.cc.Invoke(ctx, "/inflionserverpb.Job/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	Create(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	Remove(context.Context, *RemoveJobRequest) (*RemoveJobResponse, error)
}

// UnimplementedJobServer can be embedded to have forward compatible implementations.
type UnimplementedJobServer struct {
}

func (*UnimplementedJobServer) Create(ctx context.Context, req *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedJobServer) Remove(ctx context.Context, req *RemoveJobRequest) (*RemoveJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Job/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Create(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflionserverpb.Job/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Remove(ctx, req.(*RemoveJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inflionserverpb.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Job_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Job_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inflion.proto",
}
