// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow.proto

package flowpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunFlowResponse_ExitStatus int32

const (
	RunFlowResponse_SUCCESS RunFlowResponse_ExitStatus = 0
	RunFlowResponse_FAILURE RunFlowResponse_ExitStatus = 1
)

var RunFlowResponse_ExitStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var RunFlowResponse_ExitStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x RunFlowResponse_ExitStatus) String() string {
	return proto.EnumName(RunFlowResponse_ExitStatus_name, int32(x))
}

func (RunFlowResponse_ExitStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{4, 0}
}

type Flow struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flow) Reset()         { *m = Flow{} }
func (m *Flow) String() string { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()    {}
func (*Flow) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{0}
}

func (m *Flow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flow.Unmarshal(m, b)
}
func (m *Flow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flow.Marshal(b, m, deterministic)
}
func (m *Flow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flow.Merge(m, src)
}
func (m *Flow) XXX_Size() int {
	return xxx_messageInfo_Flow.Size(m)
}
func (m *Flow) XXX_DiscardUnknown() {
	xxx_messageInfo_Flow.DiscardUnknown(m)
}

var xxx_messageInfo_Flow proto.InternalMessageInfo

func (m *Flow) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Flow) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Flow) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ListFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFlowRequest) Reset()         { *m = ListFlowRequest{} }
func (m *ListFlowRequest) String() string { return proto.CompactTextString(m) }
func (*ListFlowRequest) ProtoMessage()    {}
func (*ListFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{1}
}

func (m *ListFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFlowRequest.Unmarshal(m, b)
}
func (m *ListFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFlowRequest.Marshal(b, m, deterministic)
}
func (m *ListFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFlowRequest.Merge(m, src)
}
func (m *ListFlowRequest) XXX_Size() int {
	return xxx_messageInfo_ListFlowRequest.Size(m)
}
func (m *ListFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFlowRequest proto.InternalMessageInfo

func (m *ListFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ListFlowResponse struct {
	Flows                []*Flow  `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFlowResponse) Reset()         { *m = ListFlowResponse{} }
func (m *ListFlowResponse) String() string { return proto.CompactTextString(m) }
func (*ListFlowResponse) ProtoMessage()    {}
func (*ListFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{2}
}

func (m *ListFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFlowResponse.Unmarshal(m, b)
}
func (m *ListFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFlowResponse.Marshal(b, m, deterministic)
}
func (m *ListFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFlowResponse.Merge(m, src)
}
func (m *ListFlowResponse) XXX_Size() int {
	return xxx_messageInfo_ListFlowResponse.Size(m)
}
func (m *ListFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFlowResponse proto.InternalMessageInfo

func (m *ListFlowResponse) GetFlows() []*Flow {
	if m != nil {
		return m.Flows
	}
	return nil
}

type RunFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunFlowRequest) Reset()         { *m = RunFlowRequest{} }
func (m *RunFlowRequest) String() string { return proto.CompactTextString(m) }
func (*RunFlowRequest) ProtoMessage()    {}
func (*RunFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{3}
}

func (m *RunFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunFlowRequest.Unmarshal(m, b)
}
func (m *RunFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunFlowRequest.Marshal(b, m, deterministic)
}
func (m *RunFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunFlowRequest.Merge(m, src)
}
func (m *RunFlowRequest) XXX_Size() int {
	return xxx_messageInfo_RunFlowRequest.Size(m)
}
func (m *RunFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunFlowRequest proto.InternalMessageInfo

func (m *RunFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RunFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RunFlowResponse struct {
	Status               RunFlowResponse_ExitStatus `protobuf:"varint,1,opt,name=status,proto3,enum=inflion.inflionserver.flow.v1.RunFlowResponse_ExitStatus" json:"status,omitempty"`
	Output               string                     `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RunFlowResponse) Reset()         { *m = RunFlowResponse{} }
func (m *RunFlowResponse) String() string { return proto.CompactTextString(m) }
func (*RunFlowResponse) ProtoMessage()    {}
func (*RunFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{4}
}

func (m *RunFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunFlowResponse.Unmarshal(m, b)
}
func (m *RunFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunFlowResponse.Marshal(b, m, deterministic)
}
func (m *RunFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunFlowResponse.Merge(m, src)
}
func (m *RunFlowResponse) XXX_Size() int {
	return xxx_messageInfo_RunFlowResponse.Size(m)
}
func (m *RunFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunFlowResponse proto.InternalMessageInfo

func (m *RunFlowResponse) GetStatus() RunFlowResponse_ExitStatus {
	if m != nil {
		return m.Status
	}
	return RunFlowResponse_SUCCESS
}

func (m *RunFlowResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type CreateFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFlowRequest) Reset()         { *m = CreateFlowRequest{} }
func (m *CreateFlowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFlowRequest) ProtoMessage()    {}
func (*CreateFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{5}
}

func (m *CreateFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFlowRequest.Unmarshal(m, b)
}
func (m *CreateFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFlowRequest.Marshal(b, m, deterministic)
}
func (m *CreateFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFlowRequest.Merge(m, src)
}
func (m *CreateFlowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFlowRequest.Size(m)
}
func (m *CreateFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFlowRequest proto.InternalMessageInfo

func (m *CreateFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateFlowRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type CreateFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFlowResponse) Reset()         { *m = CreateFlowResponse{} }
func (m *CreateFlowResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFlowResponse) ProtoMessage()    {}
func (*CreateFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{6}
}

func (m *CreateFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFlowResponse.Unmarshal(m, b)
}
func (m *CreateFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFlowResponse.Marshal(b, m, deterministic)
}
func (m *CreateFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFlowResponse.Merge(m, src)
}
func (m *CreateFlowResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFlowResponse.Size(m)
}
func (m *CreateFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFlowResponse proto.InternalMessageInfo

func (m *CreateFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlowRequest) Reset()         { *m = GetFlowRequest{} }
func (m *GetFlowRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlowRequest) ProtoMessage()    {}
func (*GetFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{7}
}

func (m *GetFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlowRequest.Unmarshal(m, b)
}
func (m *GetFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlowRequest.Marshal(b, m, deterministic)
}
func (m *GetFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlowRequest.Merge(m, src)
}
func (m *GetFlowRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlowRequest.Size(m)
}
func (m *GetFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlowRequest proto.InternalMessageInfo

func (m *GetFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *GetFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlowResponse) Reset()         { *m = GetFlowResponse{} }
func (m *GetFlowResponse) String() string { return proto.CompactTextString(m) }
func (*GetFlowResponse) ProtoMessage()    {}
func (*GetFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{8}
}

func (m *GetFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlowResponse.Unmarshal(m, b)
}
func (m *GetFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlowResponse.Marshal(b, m, deterministic)
}
func (m *GetFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlowResponse.Merge(m, src)
}
func (m *GetFlowResponse) XXX_Size() int {
	return xxx_messageInfo_GetFlowResponse.Size(m)
}
func (m *GetFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlowResponse proto.InternalMessageInfo

func (m *GetFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetFlowResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFlowRequest) Reset()         { *m = UpdateFlowRequest{} }
func (m *UpdateFlowRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFlowRequest) ProtoMessage()    {}
func (*UpdateFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{9}
}

func (m *UpdateFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFlowRequest.Unmarshal(m, b)
}
func (m *UpdateFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFlowRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFlowRequest.Merge(m, src)
}
func (m *UpdateFlowRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFlowRequest.Size(m)
}
func (m *UpdateFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFlowRequest proto.InternalMessageInfo

func (m *UpdateFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *UpdateFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateFlowRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFlowResponse) Reset()         { *m = UpdateFlowResponse{} }
func (m *UpdateFlowResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFlowResponse) ProtoMessage()    {}
func (*UpdateFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{10}
}

func (m *UpdateFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFlowResponse.Unmarshal(m, b)
}
func (m *UpdateFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFlowResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFlowResponse.Merge(m, src)
}
func (m *UpdateFlowResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFlowResponse.Size(m)
}
func (m *UpdateFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFlowResponse proto.InternalMessageInfo

func (m *UpdateFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFlowRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFlowRequest) Reset()         { *m = DeleteFlowRequest{} }
func (m *DeleteFlowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFlowRequest) ProtoMessage()    {}
func (*DeleteFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{11}
}

func (m *DeleteFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFlowRequest.Unmarshal(m, b)
}
func (m *DeleteFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFlowRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFlowRequest.Merge(m, src)
}
func (m *DeleteFlowRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFlowRequest.Size(m)
}
func (m *DeleteFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFlowRequest proto.InternalMessageInfo

func (m *DeleteFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *DeleteFlowRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFlowResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFlowResponse) Reset()         { *m = DeleteFlowResponse{} }
func (m *DeleteFlowResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFlowResponse) ProtoMessage()    {}
func (*DeleteFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{12}
}

func (m *DeleteFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFlowResponse.Unmarshal(m, b)
}
func (m *DeleteFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFlowResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFlowResponse.Merge(m, src)
}
func (m *DeleteFlowResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFlowResponse.Size(m)
}
func (m *DeleteFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFlowResponse proto.InternalMessageInfo

func (m *DeleteFlowResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("inflion.inflionserver.flow.v1.RunFlowResponse_ExitStatus", RunFlowResponse_ExitStatus_name, RunFlowResponse_ExitStatus_value)
	proto.RegisterType((*Flow)(nil), "inflion.inflionserver.flow.v1.Flow")
	proto.RegisterType((*ListFlowRequest)(nil), "inflion.inflionserver.flow.v1.ListFlowRequest")
	proto.RegisterType((*ListFlowResponse)(nil), "inflion.inflionserver.flow.v1.ListFlowResponse")
	proto.RegisterType((*RunFlowRequest)(nil), "inflion.inflionserver.flow.v1.RunFlowRequest")
	proto.RegisterType((*RunFlowResponse)(nil), "inflion.inflionserver.flow.v1.RunFlowResponse")
	proto.RegisterType((*CreateFlowRequest)(nil), "inflion.inflionserver.flow.v1.CreateFlowRequest")
	proto.RegisterType((*CreateFlowResponse)(nil), "inflion.inflionserver.flow.v1.CreateFlowResponse")
	proto.RegisterType((*GetFlowRequest)(nil), "inflion.inflionserver.flow.v1.GetFlowRequest")
	proto.RegisterType((*GetFlowResponse)(nil), "inflion.inflionserver.flow.v1.GetFlowResponse")
	proto.RegisterType((*UpdateFlowRequest)(nil), "inflion.inflionserver.flow.v1.UpdateFlowRequest")
	proto.RegisterType((*UpdateFlowResponse)(nil), "inflion.inflionserver.flow.v1.UpdateFlowResponse")
	proto.RegisterType((*DeleteFlowRequest)(nil), "inflion.inflionserver.flow.v1.DeleteFlowRequest")
	proto.RegisterType((*DeleteFlowResponse)(nil), "inflion.inflionserver.flow.v1.DeleteFlowResponse")
}

func init() {
	proto.RegisterFile("flow.proto", fileDescriptor_bb3fc33c49933823)
}

var fileDescriptor_bb3fc33c49933823 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0x70, 0x9a, 0x09, 0x24, 0xf1, 0x80, 0xc0, 0x8a, 0x40, 0xaa, 0x96, 0x0a, 0x55,
	0x45, 0xd8, 0x24, 0x88, 0x43, 0x23, 0x71, 0x28, 0x69, 0x5a, 0x55, 0x2a, 0x87, 0x3a, 0xca, 0x85,
	0x9b, 0x43, 0x36, 0x95, 0x91, 0xe5, 0x35, 0xf6, 0x3a, 0x05, 0x24, 0x84, 0x54, 0x4e, 0x9c, 0xf9,
	0x0b, 0xfc, 0x23, 0xfe, 0x02, 0x3f, 0x04, 0xed, 0xfa, 0x23, 0x21, 0x4e, 0xb1, 0xdb, 0x53, 0xbc,
	0xab, 0x79, 0xf3, 0xde, 0x9b, 0x7d, 0xa3, 0x00, 0xcc, 0x5d, 0x76, 0x61, 0xf8, 0x01, 0xe3, 0x0c,
	0x1f, 0x3b, 0xde, 0xdc, 0x75, 0x98, 0x67, 0x24, 0xbf, 0x21, 0x0d, 0x16, 0x34, 0x30, 0x64, 0xc5,
	0xa2, 0xd7, 0x7d, 0x74, 0xce, 0xd8, 0xb9, 0x4b, 0x4d, 0xdb, 0x77, 0x4c, 0xdb, 0xf3, 0x18, 0xb7,
	0xb9, 0x28, 0x8a, 0xc1, 0xe4, 0x10, 0x6a, 0x47, 0x2e, 0xbb, 0x40, 0x1d, 0xea, 0x7e, 0xc0, 0x3e,
	0xd0, 0xf7, 0x5c, 0x57, 0xb6, 0x95, 0xdd, 0x86, 0x95, 0x1e, 0xb1, 0x05, 0x15, 0x67, 0xa6, 0x57,
	0xe4, 0x65, 0xc5, 0x99, 0x21, 0x42, 0x6d, 0xca, 0x66, 0x9f, 0xf5, 0xaa, 0xbc, 0x91, 0xdf, 0xe4,
	0x19, 0xb4, 0x4f, 0x9d, 0x90, 0x8b, 0x4e, 0x16, 0xfd, 0x18, 0xd1, 0x90, 0x5f, 0xdd, 0x90, 0xbc,
	0x85, 0xce, 0xb2, 0x38, 0xf4, 0x85, 0x60, 0xdc, 0x87, 0xdb, 0x42, 0x6f, 0xa8, 0x2b, 0xdb, 0xd5,
	0xdd, 0x66, 0xff, 0x89, 0xf1, 0x5f, 0x4f, 0x86, 0xc4, 0xc6, 0x08, 0x32, 0x80, 0x96, 0x15, 0x79,
	0xa5, 0xa8, 0xd7, 0xbd, 0x90, 0x5f, 0x0a, 0xb4, 0x33, 0x70, 0x22, 0xe5, 0x0c, 0xd4, 0x90, 0xdb,
	0x3c, 0x0a, 0x25, 0xb8, 0xd5, 0xdf, 0x2f, 0xd0, 0xb2, 0x86, 0x37, 0x46, 0x9f, 0x1c, 0x3e, 0x96,
	0x0d, 0xac, 0xa4, 0x11, 0x3e, 0x00, 0x95, 0x45, 0xdc, 0x8f, 0x78, 0x42, 0x9d, 0x9c, 0xc8, 0x53,
	0x80, 0x65, 0x35, 0x36, 0xa1, 0x3e, 0x9e, 0x0c, 0x87, 0xa3, 0xf1, 0xb8, 0x73, 0x4b, 0x1c, 0x8e,
	0x0e, 0x4e, 0x4e, 0x27, 0xd6, 0xa8, 0xa3, 0x90, 0x03, 0xd0, 0x86, 0x01, 0xb5, 0x39, 0x2d, 0xe7,
	0x32, 0x7d, 0xa1, 0xca, 0xca, 0x0b, 0xed, 0x00, 0xae, 0xb6, 0x48, 0xbc, 0xc6, 0xf3, 0x50, 0xb2,
	0x79, 0x0c, 0xa0, 0x75, 0x4c, 0xf9, 0xcd, 0x66, 0xf9, 0x0a, 0xda, 0x19, 0x76, 0x73, 0xfb, 0x8d,
	0xc2, 0xce, 0x40, 0x9b, 0xf8, 0xb3, 0xd2, 0xde, 0xca, 0xa4, 0x71, 0x07, 0x70, 0xb5, 0xe5, 0x15,
	0x5e, 0x5f, 0x83, 0x76, 0x48, 0x5d, 0x7a, 0x43, 0x62, 0x41, 0xb2, 0x0a, 0xdf, 0x4c, 0xd2, 0xff,
	0xa1, 0xc2, 0x96, 0x28, 0x38, 0xf1, 0xe6, 0x0c, 0xbf, 0x40, 0x4d, 0x04, 0x1f, 0x8d, 0x82, 0x44,
	0xad, 0xad, 0x52, 0xd7, 0x2c, 0x5d, 0x1f, 0xab, 0x20, 0xda, 0xe5, 0xef, 0x3f, 0x3f, 0x2b, 0x4d,
	0x6c, 0x98, 0x8b, 0x9e, 0x29, 0xb7, 0x04, 0xbf, 0x42, 0xd5, 0x8a, 0x3c, 0x7c, 0x5e, 0x36, 0xcc,
	0x31, 0xb3, 0x71, 0xbd, 0xec, 0x93, 0x87, 0x92, 0x58, 0x23, 0x77, 0x52, 0x62, 0x33, 0x88, 0xbc,
	0x81, 0xb2, 0x87, 0xdf, 0x15, 0x50, 0xe3, 0xfc, 0xe1, 0x8b, 0x82, 0x9e, 0xb9, 0xa4, 0x77, 0x7b,
	0xd7, 0x40, 0x24, 0x42, 0xee, 0x4b, 0x21, 0x2d, 0xb2, 0x9c, 0x80, 0x50, 0xb1, 0x80, 0xea, 0x31,
	0xe5, 0x85, 0x43, 0xf8, 0x77, 0x05, 0x0a, 0x87, 0xb0, 0x96, 0x7a, 0xd2, 0x91, 0xdc, 0x80, 0x5b,
	0x29, 0x37, 0x5e, 0x2a, 0xa0, 0xc6, 0x89, 0x2c, 0x74, 0x9f, 0xdb, 0x85, 0x42, 0xf7, 0xf9, 0xa8,
	0x93, 0x7b, 0x52, 0xc1, 0xdd, 0x6e, 0xa6, 0x40, 0x98, 0xff, 0x06, 0x6a, 0x1c, 0xd8, 0x42, 0x0d,
	0xb9, 0xb5, 0x28, 0xd4, 0x90, 0xdf, 0x84, 0x74, 0x0a, 0x7b, 0x99, 0x86, 0x37, 0x8d, 0x77, 0x75,
	0xf9, 0xe1, 0x4f, 0xa7, 0xaa, 0xfc, 0xf3, 0x79, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x76,
	0x80, 0xc8, 0xc7, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FlowInfoClient is the client API for FlowInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlowInfoClient interface {
	List(ctx context.Context, in *ListFlowRequest, opts ...grpc.CallOption) (*ListFlowResponse, error)
	Run(ctx context.Context, in *RunFlowRequest, opts ...grpc.CallOption) (*RunFlowResponse, error)
	Create(ctx context.Context, in *CreateFlowRequest, opts ...grpc.CallOption) (*CreateFlowResponse, error)
	Get(ctx context.Context, in *GetFlowRequest, opts ...grpc.CallOption) (*GetFlowResponse, error)
	Update(ctx context.Context, in *UpdateFlowRequest, opts ...grpc.CallOption) (*UpdateFlowResponse, error)
	Delete(ctx context.Context, in *DeleteFlowRequest, opts ...grpc.CallOption) (*DeleteFlowResponse, error)
}

type flowInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowInfoClient(cc grpc.ClientConnInterface) FlowInfoClient {
	return &flowInfoClient{cc}
}

func (c *flowInfoClient) List(ctx context.Context, in *ListFlowRequest, opts ...grpc.CallOption) (*ListFlowResponse, error) {
	out := new(ListFlowResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.flow.v1.FlowInfo/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowInfoClient) Run(ctx context.Context, in *RunFlowRequest, opts ...grpc.CallOption) (*RunFlowResponse, error) {
	out := new(RunFlowResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.flow.v1.FlowInfo/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowInfoClient) Create(ctx context.Context, in *CreateFlowRequest, opts ...grpc.CallOption) (*CreateFlowResponse, error) {
	out := new(CreateFlowResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.flow.v1.FlowInfo/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowInfoClient) Get(ctx context.Context, in *GetFlowRequest, opts ...grpc.CallOption) (*GetFlowResponse, error) {
	out := new(GetFlowResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.flow.v1.FlowInfo/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowInfoClient) Update(ctx context.Context, in *UpdateFlowRequest, opts ...grpc.CallOption) (*UpdateFlowResponse, error) {
	out := new(UpdateFlowResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.flow.v1.FlowInfo/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowInfoClient) Delete(ctx context.Context, in *DeleteFlowRequest, opts ...grpc.CallOption) (*DeleteFlowResponse, error) {
	out := new(DeleteFlowResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.flow.v1.FlowInfo/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowInfoServer is the server API for FlowInfo service.
type FlowInfoServer interface {
	List(context.Context, *ListFlowRequest) (*ListFlowResponse, error)
	Run(context.Context, *RunFlowRequest) (*RunFlowResponse, error)
	Create(context.Context, *CreateFlowRequest) (*CreateFlowResponse, error)
	Get(context.Context, *GetFlowRequest) (*GetFlowResponse, error)
	Update(context.Context, *UpdateFlowRequest) (*UpdateFlowResponse, error)
	Delete(context.Context, *DeleteFlowRequest) (*DeleteFlowResponse, error)
}

// UnimplementedFlowInfoServer can be embedded to have forward compatible implementations.
type UnimplementedFlowInfoServer struct {
}

func (*UnimplementedFlowInfoServer) List(ctx context.Context, req *ListFlowRequest) (*ListFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedFlowInfoServer) Run(ctx context.Context, req *RunFlowRequest) (*RunFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (*UnimplementedFlowInfoServer) Create(ctx context.Context, req *CreateFlowRequest) (*CreateFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedFlowInfoServer) Get(ctx context.Context, req *GetFlowRequest) (*GetFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedFlowInfoServer) Update(ctx context.Context, req *UpdateFlowRequest) (*UpdateFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedFlowInfoServer) Delete(ctx context.Context, req *DeleteFlowRequest) (*DeleteFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterFlowInfoServer(s *grpc.Server, srv FlowInfoServer) {
	s.RegisterService(&_FlowInfo_serviceDesc, srv)
}

func _FlowInfo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowInfoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.flow.v1.FlowInfo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowInfoServer).List(ctx, req.(*ListFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowInfo_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowInfoServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.flow.v1.FlowInfo/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowInfoServer).Run(ctx, req.(*RunFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.flow.v1.FlowInfo/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowInfoServer).Create(ctx, req.(*CreateFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowInfo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowInfoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.flow.v1.FlowInfo/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowInfoServer).Get(ctx, req.(*GetFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowInfo_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowInfoServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.flow.v1.FlowInfo/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowInfoServer).Update(ctx, req.(*UpdateFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowInfo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowInfoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.flow.v1.FlowInfo/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowInfoServer).Delete(ctx, req.(*DeleteFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlowInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inflion.inflionserver.flow.v1.FlowInfo",
	HandlerType: (*FlowInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _FlowInfo_List_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _FlowInfo_Run_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _FlowInfo_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _FlowInfo_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _FlowInfo_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FlowInfo_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flow.proto",
}
