// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package jobserverpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	FlowId               string   `protobuf:"bytes,3,opt,name=flowId,proto3" json:"flowId,omitempty"`
	Schedule             string   `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateJobRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *CreateJobRequest) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

type CreateJobResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobRequest) Reset()         { *m = RemoveJobRequest{} }
func (m *RemoveJobRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveJobRequest) ProtoMessage()    {}
func (*RemoveJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *RemoveJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobRequest.Unmarshal(m, b)
}
func (m *RemoveJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobRequest.Marshal(b, m, deterministic)
}
func (m *RemoveJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobRequest.Merge(m, src)
}
func (m *RemoveJobRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveJobRequest.Size(m)
}
func (m *RemoveJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobRequest proto.InternalMessageInfo

func (m *RemoveJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoveJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type RemoveJobResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobResponse) Reset()         { *m = RemoveJobResponse{} }
func (m *RemoveJobResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveJobResponse) ProtoMessage()    {}
func (*RemoveJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *RemoveJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobResponse.Unmarshal(m, b)
}
func (m *RemoveJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobResponse.Marshal(b, m, deterministic)
}
func (m *RemoveJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobResponse.Merge(m, src)
}
func (m *RemoveJobResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveJobResponse.Size(m)
}
func (m *RemoveJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobResponse proto.InternalMessageInfo

func (m *RemoveJobResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateJobRequest)(nil), "jobserverpb.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "jobserverpb.CreateJobResponse")
	proto.RegisterType((*RemoveJobRequest)(nil), "jobserverpb.RemoveJobRequest")
	proto.RegisterType((*RemoveJobResponse)(nil), "jobserverpb.RemoveJobResponse")
}

func init() {
	proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead)
}

var fileDescriptor_f32c477d91a04ead = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xca, 0x4f, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0xca, 0x4f, 0x2a, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d,
	0x2a, 0x48, 0x92, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f,
	0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x55, 0x2a, 0xe0, 0x12,
	0x70, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0xf5, 0xca, 0x4f, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c,
	0x11, 0x92, 0xe0, 0x62, 0x2f, 0x28, 0xca, 0xcf, 0x4a, 0x4d, 0x2e, 0x91, 0x60, 0x52, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0x71, 0x85, 0xc4, 0xb8, 0xd8, 0xd2, 0x72, 0xf2, 0xcb, 0x3d, 0x53, 0x24, 0x98,
	0xc1, 0x12, 0x50, 0x9e, 0x90, 0x14, 0x17, 0x47, 0x71, 0x72, 0x46, 0x6a, 0x4a, 0x69, 0x4e, 0xaa,
	0x04, 0x0b, 0x58, 0x06, 0xce, 0x57, 0x52, 0xe6, 0x12, 0x44, 0xb2, 0xb1, 0xb8, 0x20, 0x3f, 0xaf,
	0x38, 0x15, 0xc9, 0x4a, 0x4e, 0x90, 0x95, 0x4a, 0x36, 0x5c, 0x02, 0x41, 0xa9, 0xb9, 0xf9, 0x65,
	0x64, 0x39, 0x0b, 0x64, 0x05, 0x92, 0x6e, 0x0c, 0x2b, 0xc0, 0xda, 0x8d, 0x0e, 0x32, 0x72, 0x31,
	0x7b, 0xe5, 0x27, 0x09, 0xc5, 0x70, 0xb1, 0x41, 0xdc, 0x23, 0x24, 0xab, 0x87, 0x14, 0x6e, 0x7a,
	0xe8, 0xc1, 0x22, 0x25, 0x87, 0x4b, 0x1a, 0x62, 0x81, 0x92, 0x70, 0xd3, 0xe5, 0x27, 0x93, 0x99,
	0x78, 0x95, 0x38, 0xf4, 0xcb, 0x0c, 0xf5, 0x41, 0x4a, 0xad, 0x18, 0xb5, 0x40, 0xa6, 0x43, 0x9c,
	0x82, 0x66, 0x3a, 0xba, 0xef, 0xd0, 0x4c, 0xc7, 0x70, 0x3e, 0xcc, 0x74, 0x2d, 0x64, 0xd3, 0x93,
	0xd8, 0xc0, 0x91, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xd7, 0xde, 0x37, 0xfc, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error)
}

type jobClient struct {
	cc grpc.ClientConnInterface
}

func NewJobClient(cc grpc.ClientConnInterface) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/jobserverpb.Job/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error) {
	out := new(RemoveJobResponse)
	err := c.cc.Invoke(ctx, "/jobserverpb.Job/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	Create(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	Remove(context.Context, *RemoveJobRequest) (*RemoveJobResponse, error)
}

// UnimplementedJobServer can be embedded to have forward compatible implementations.
type UnimplementedJobServer struct {
}

func (*UnimplementedJobServer) Create(ctx context.Context, req *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedJobServer) Remove(ctx context.Context, req *RemoveJobRequest) (*RemoveJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobserverpb.Job/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Create(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobserverpb.Job/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Remove(ctx, req.(*RemoveJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobserverpb.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Job_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Job_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
