// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jobserver.proto

package jobserverpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	FlowId               string   `protobuf:"bytes,3,opt,name=flowId,proto3" json:"flowId,omitempty"`
	Schedule             string   `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b210118a879655, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Job) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Job) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *Job) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

type ListJobsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsRequest) Reset()         { *m = ListJobsRequest{} }
func (m *ListJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ListJobsRequest) ProtoMessage()    {}
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b210118a879655, []int{1}
}

func (m *ListJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsRequest.Unmarshal(m, b)
}
func (m *ListJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsRequest.Marshal(b, m, deterministic)
}
func (m *ListJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsRequest.Merge(m, src)
}
func (m *ListJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ListJobsRequest.Size(m)
}
func (m *ListJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsRequest proto.InternalMessageInfo

func (m *ListJobsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ListJobsResponse struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsResponse) Reset()         { *m = ListJobsResponse{} }
func (m *ListJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ListJobsResponse) ProtoMessage()    {}
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b210118a879655, []int{2}
}

func (m *ListJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsResponse.Unmarshal(m, b)
}
func (m *ListJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsResponse.Marshal(b, m, deterministic)
}
func (m *ListJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsResponse.Merge(m, src)
}
func (m *ListJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ListJobsResponse.Size(m)
}
func (m *ListJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsResponse proto.InternalMessageInfo

func (m *ListJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type CreateJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	FlowId               string   `protobuf:"bytes,3,opt,name=flowId,proto3" json:"flowId,omitempty"`
	Schedule             string   `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b210118a879655, []int{3}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateJobRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *CreateJobRequest) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

type CreateJobResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b210118a879655, []int{4}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobRequest) Reset()         { *m = RemoveJobRequest{} }
func (m *RemoveJobRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveJobRequest) ProtoMessage()    {}
func (*RemoveJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b210118a879655, []int{5}
}

func (m *RemoveJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobRequest.Unmarshal(m, b)
}
func (m *RemoveJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobRequest.Marshal(b, m, deterministic)
}
func (m *RemoveJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobRequest.Merge(m, src)
}
func (m *RemoveJobRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveJobRequest.Size(m)
}
func (m *RemoveJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobRequest proto.InternalMessageInfo

func (m *RemoveJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoveJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type RemoveJobResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobResponse) Reset()         { *m = RemoveJobResponse{} }
func (m *RemoveJobResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveJobResponse) ProtoMessage()    {}
func (*RemoveJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b210118a879655, []int{6}
}

func (m *RemoveJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobResponse.Unmarshal(m, b)
}
func (m *RemoveJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobResponse.Marshal(b, m, deterministic)
}
func (m *RemoveJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobResponse.Merge(m, src)
}
func (m *RemoveJobResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveJobResponse.Size(m)
}
func (m *RemoveJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobResponse proto.InternalMessageInfo

func (m *RemoveJobResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Job)(nil), "jobserverpb.Job")
	proto.RegisterType((*ListJobsRequest)(nil), "jobserverpb.ListJobsRequest")
	proto.RegisterType((*ListJobsResponse)(nil), "jobserverpb.ListJobsResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "jobserverpb.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "jobserverpb.CreateJobResponse")
	proto.RegisterType((*RemoveJobRequest)(nil), "jobserverpb.RemoveJobRequest")
	proto.RegisterType((*RemoveJobResponse)(nil), "jobserverpb.RemoveJobResponse")
}

func init() {
	proto.RegisterFile("jobserver.proto", fileDescriptor_b8b210118a879655)
}

var fileDescriptor_b8b210118a879655 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0xd3, 0x82, 0x08, 0x97, 0x28, 0x75, 0x4c, 0x4c, 0xd3, 0xa0, 0x21, 0xa3, 0x0b, 0x82,
	0x09, 0x8d, 0xb8, 0x31, 0xc6, 0x9d, 0x2b, 0x1b, 0x57, 0x75, 0xe3, 0xc2, 0x4d, 0x87, 0x5e, 0xb1,
	0x04, 0x7b, 0x6b, 0x67, 0xc0, 0xbd, 0xaf, 0xe0, 0x0b, 0xf8, 0x4e, 0xbe, 0x82, 0x0f, 0x62, 0xfa,
	0x03, 0xb4, 0x25, 0x6c, 0x4c, 0x5c, 0xce, 0x9c, 0x7b, 0xcf, 0x37, 0xe7, 0xb4, 0xd0, 0x99, 0x92,
	0x90, 0x18, 0x2f, 0x30, 0x1e, 0x46, 0x31, 0x29, 0x62, 0xed, 0xd5, 0x45, 0x24, 0xac, 0xee, 0x84,
	0x68, 0x32, 0x43, 0xdb, 0x8b, 0x02, 0xdb, 0x0b, 0x43, 0x52, 0x9e, 0x0a, 0x28, 0x94, 0xd9, 0x28,
	0x1f, 0x43, 0xcd, 0x21, 0xc1, 0xf6, 0x41, 0x0f, 0x7c, 0x53, 0xeb, 0x69, 0xfd, 0x1d, 0x57, 0x0f,
	0x7c, 0x66, 0xc2, 0x6e, 0x14, 0xd3, 0x14, 0xc7, 0xca, 0xd4, 0x7b, 0x5a, 0xbf, 0xe5, 0x2e, 0x8f,
	0xec, 0x08, 0x1a, 0xcf, 0x33, 0x7a, 0xbf, 0xf3, 0xcd, 0x5a, 0x2a, 0xe4, 0x27, 0x66, 0x41, 0x53,
	0x8e, 0x5f, 0xd0, 0x9f, 0xcf, 0xd0, 0xac, 0xa7, 0xca, 0xea, 0xcc, 0xcf, 0xa1, 0x73, 0x1f, 0x48,
	0xe5, 0x90, 0x90, 0x2e, 0xbe, 0xcd, 0x51, 0xaa, 0x22, 0x40, 0x2b, 0x01, 0xf8, 0x15, 0x18, 0xeb,
	0x61, 0x19, 0x51, 0x28, 0x91, 0x9d, 0x41, 0x3d, 0x89, 0x64, 0x6a, 0xbd, 0x5a, 0xbf, 0x3d, 0x32,
	0x86, 0x85, 0x7c, 0x43, 0x87, 0x84, 0x9b, 0xaa, 0x3c, 0x02, 0xe3, 0x36, 0x46, 0x4f, 0x61, 0x72,
	0x95, 0x73, 0xfe, 0x37, 0xd8, 0x29, 0x1c, 0x14, 0x88, 0xf9, 0x63, 0xd7, 0xc8, 0x56, 0x82, 0xe4,
	0x37, 0x60, 0xb8, 0xf8, 0x4a, 0x8b, 0x3f, 0x3d, 0x2b, 0x41, 0x14, 0xb6, 0x37, 0x10, 0xe9, 0xfa,
	0xe8, 0x4b, 0x87, 0xa6, 0x43, 0xe2, 0x41, 0x51, 0x8c, 0xec, 0x11, 0xea, 0x49, 0x81, 0xac, 0x5b,
	0xaa, 0xa9, 0xf2, 0x01, 0xac, 0xe3, 0x2d, 0x6a, 0x46, 0xe0, 0x87, 0x1f, 0xdf, 0x3f, 0x9f, 0xfa,
	0x1e, 0x6b, 0xda, 0x8b, 0x0b, 0x3b, 0x99, 0xbc, 0xd6, 0x06, 0xec, 0x09, 0x1a, 0x59, 0x5c, 0x56,
	0xde, 0xae, 0xb6, 0x6e, 0x9d, 0x6c, 0x93, 0xcb, 0xee, 0xbc, 0xea, 0x9e, 0x25, 0xad, 0xb8, 0x57,
	0xcb, 0xab, 0xb8, 0x6f, 0xb4, 0xb3, 0x74, 0x1f, 0x14, 0xdd, 0x45, 0x23, 0xfd, 0xdf, 0x2f, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xab, 0x2e, 0xe2, 0x0e, 0x2d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JobStoreClient is the client API for JobStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobStoreClient interface {
	List(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error)
}

type jobStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewJobStoreClient(cc grpc.ClientConnInterface) JobStoreClient {
	return &jobStoreClient{cc}
}

func (c *jobStoreClient) List(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, "/jobserverpb.JobStore/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobStoreClient) Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/jobserverpb.JobStore/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobStoreClient) Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error) {
	out := new(RemoveJobResponse)
	err := c.cc.Invoke(ctx, "/jobserverpb.JobStore/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobStoreServer is the server API for JobStore service.
type JobStoreServer interface {
	List(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	Create(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	Remove(context.Context, *RemoveJobRequest) (*RemoveJobResponse, error)
}

// UnimplementedJobStoreServer can be embedded to have forward compatible implementations.
type UnimplementedJobStoreServer struct {
}

func (*UnimplementedJobStoreServer) List(ctx context.Context, req *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedJobStoreServer) Create(ctx context.Context, req *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedJobStoreServer) Remove(ctx context.Context, req *RemoveJobRequest) (*RemoveJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterJobStoreServer(s *grpc.Server, srv JobStoreServer) {
	s.RegisterService(&_JobStore_serviceDesc, srv)
}

func _JobStore_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobStoreServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobserverpb.JobStore/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobStoreServer).List(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobStore_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobStoreServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobserverpb.JobStore/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobStoreServer).Create(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobStore_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobStoreServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobserverpb.JobStore/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobStoreServer).Remove(ctx, req.(*RemoveJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobserverpb.JobStore",
	HandlerType: (*JobStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _JobStore_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _JobStore_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _JobStore_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobserver.proto",
}
