// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package jobpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	FlowId               string   `protobuf:"bytes,3,opt,name=flowId,proto3" json:"flowId,omitempty"`
	Schedule             string   `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Job) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Job) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *Job) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

type ListJobsRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsRequest) Reset()         { *m = ListJobsRequest{} }
func (m *ListJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ListJobsRequest) ProtoMessage()    {}
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *ListJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsRequest.Unmarshal(m, b)
}
func (m *ListJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsRequest.Marshal(b, m, deterministic)
}
func (m *ListJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsRequest.Merge(m, src)
}
func (m *ListJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ListJobsRequest.Size(m)
}
func (m *ListJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsRequest proto.InternalMessageInfo

func (m *ListJobsRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type ListJobsResponse struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsResponse) Reset()         { *m = ListJobsResponse{} }
func (m *ListJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ListJobsResponse) ProtoMessage()    {}
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *ListJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsResponse.Unmarshal(m, b)
}
func (m *ListJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsResponse.Marshal(b, m, deterministic)
}
func (m *ListJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsResponse.Merge(m, src)
}
func (m *ListJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ListJobsResponse.Size(m)
}
func (m *ListJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsResponse proto.InternalMessageInfo

func (m *ListJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type CreateJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	FlowId               string   `protobuf:"bytes,3,opt,name=flowId,proto3" json:"flowId,omitempty"`
	Schedule             string   `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateJobRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *CreateJobRequest) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

type CreateJobResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{4}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveJobRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobRequest) Reset()         { *m = RemoveJobRequest{} }
func (m *RemoveJobRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveJobRequest) ProtoMessage()    {}
func (*RemoveJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{5}
}

func (m *RemoveJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobRequest.Unmarshal(m, b)
}
func (m *RemoveJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobRequest.Marshal(b, m, deterministic)
}
func (m *RemoveJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobRequest.Merge(m, src)
}
func (m *RemoveJobRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveJobRequest.Size(m)
}
func (m *RemoveJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobRequest proto.InternalMessageInfo

func (m *RemoveJobRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoveJobRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type RemoveJobResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveJobResponse) Reset()         { *m = RemoveJobResponse{} }
func (m *RemoveJobResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveJobResponse) ProtoMessage()    {}
func (*RemoveJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{6}
}

func (m *RemoveJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveJobResponse.Unmarshal(m, b)
}
func (m *RemoveJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveJobResponse.Marshal(b, m, deterministic)
}
func (m *RemoveJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveJobResponse.Merge(m, src)
}
func (m *RemoveJobResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveJobResponse.Size(m)
}
func (m *RemoveJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveJobResponse proto.InternalMessageInfo

func (m *RemoveJobResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Job)(nil), "inflion.inflionserver.job.v1.Job")
	proto.RegisterType((*ListJobsRequest)(nil), "inflion.inflionserver.job.v1.ListJobsRequest")
	proto.RegisterType((*ListJobsResponse)(nil), "inflion.inflionserver.job.v1.ListJobsResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "inflion.inflionserver.job.v1.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "inflion.inflionserver.job.v1.CreateJobResponse")
	proto.RegisterType((*RemoveJobRequest)(nil), "inflion.inflionserver.job.v1.RemoveJobRequest")
	proto.RegisterType((*RemoveJobResponse)(nil), "inflion.inflionserver.job.v1.RemoveJobResponse")
}

func init() {
	proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead)
}

var fileDescriptor_f32c477d91a04ead = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x4e, 0xab, 0x40,
	0x14, 0x86, 0x03, 0xf4, 0xd2, 0xf6, 0xdc, 0xdc, 0x7b, 0x7b, 0xc7, 0xc4, 0x10, 0xd2, 0x45, 0xc5,
	0x4d, 0x53, 0x23, 0xa4, 0x35, 0x6e, 0x8c, 0x2b, 0x5d, 0x95, 0xb8, 0x62, 0xe9, 0x8e, 0x29, 0xd3,
	0x4a, 0x83, 0x1c, 0x64, 0xa6, 0x98, 0xb8, 0x70, 0x61, 0xe2, 0x13, 0xf8, 0x68, 0xbe, 0x82, 0x0f,
	0x62, 0x06, 0xa8, 0xa5, 0x34, 0x69, 0x1b, 0x13, 0x57, 0x70, 0x98, 0xff, 0xf0, 0x9d, 0xf3, 0xff,
	0x19, 0x68, 0xcf, 0x91, 0xda, 0x49, 0x8a, 0x02, 0x49, 0x37, 0x8c, 0xa7, 0x51, 0x88, 0xb1, 0x5d,
	0x3e, 0x39, 0x4b, 0x33, 0x96, 0xda, 0x52, 0x90, 0x0d, 0xcd, 0xee, 0x0c, 0x71, 0x16, 0x31, 0xc7,
	0x4f, 0x42, 0xc7, 0x8f, 0x63, 0x14, 0xbe, 0x90, 0x9a, 0xa2, 0xd7, 0x9a, 0x80, 0xe6, 0x22, 0x25,
	0x7f, 0x41, 0x0d, 0x03, 0x43, 0xe9, 0x29, 0xfd, 0x5f, 0x9e, 0x1a, 0x06, 0xc4, 0x80, 0x66, 0x92,
	0xe2, 0x9c, 0x4d, 0x84, 0xa1, 0xf6, 0x94, 0x7e, 0xdb, 0x5b, 0x96, 0xe4, 0x10, 0xf4, 0x69, 0x84,
	0x8f, 0xe3, 0xc0, 0xd0, 0xf2, 0x83, 0xb2, 0x22, 0x26, 0xb4, 0xf8, 0xe4, 0x8e, 0x05, 0x8b, 0x88,
	0x19, 0x8d, 0xfc, 0xe4, 0xab, 0xb6, 0x4e, 0xe0, 0xdf, 0x4d, 0xc8, 0x85, 0x8b, 0x94, 0x7b, 0xec,
	0x61, 0xc1, 0xb8, 0xa8, 0x02, 0x94, 0x35, 0x80, 0x35, 0x86, 0xce, 0x4a, 0xcc, 0x13, 0xb9, 0x0e,
	0x39, 0x87, 0xc6, 0x1c, 0x29, 0x37, 0x94, 0x9e, 0xd6, 0xff, 0x3d, 0x3a, 0xb2, 0xb7, 0x2d, 0x6c,
	0xbb, 0x48, 0xbd, 0x5c, 0x6e, 0x25, 0xd0, 0xb9, 0x4e, 0x99, 0x2f, 0x98, 0xfc, 0x54, 0x82, 0x7f,
	0x76, 0xd3, 0x63, 0xf8, 0x5f, 0x21, 0x96, 0xd3, 0xaf, 0x90, 0x6d, 0x89, 0xb4, 0x2e, 0xa1, 0xe3,
	0xb1, 0x7b, 0xcc, 0xbe, 0x35, 0x96, 0x44, 0x54, 0xba, 0x37, 0x10, 0x79, 0xfb, 0xe8, 0x55, 0x83,
	0xa6, 0x8b, 0x74, 0x1c, 0x4f, 0x91, 0x3c, 0x41, 0x43, 0x1a, 0x4a, 0x4e, 0xb7, 0xdb, 0x56, 0x4b,
	0xc8, 0xb4, 0xf7, 0x95, 0x17, 0x23, 0x58, 0x07, 0x2f, 0xef, 0x1f, 0x6f, 0xea, 0x1f, 0xd2, 0x72,
	0xb2, 0xa1, 0x23, 0xed, 0xbf, 0x50, 0x06, 0xe4, 0x19, 0xf4, 0xc2, 0x0f, 0xb2, 0xe3, 0x77, 0xf5,
	0x9c, 0x4c, 0x67, 0x6f, 0xfd, 0x3a, 0xdf, 0xaa, 0xf3, 0x0b, 0xb3, 0x76, 0xf1, 0xeb, 0x81, 0xec,
	0xe2, 0x6f, 0x44, 0xb0, 0xe4, 0x0f, 0xaa, 0xfc, 0xab, 0xd6, 0xad, 0x2e, 0xdf, 0x13, 0x4a, 0xf5,
	0xfc, 0xbe, 0x9d, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x4b, 0xbb, 0x5d, 0xb8, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JobInfoClient is the client API for JobInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobInfoClient interface {
	List(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error)
}

type jobInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewJobInfoClient(cc grpc.ClientConnInterface) JobInfoClient {
	return &jobInfoClient{cc}
}

func (c *jobInfoClient) List(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.job.v1.JobInfo/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobInfoClient) Create(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.job.v1.JobInfo/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobInfoClient) Remove(ctx context.Context, in *RemoveJobRequest, opts ...grpc.CallOption) (*RemoveJobResponse, error) {
	out := new(RemoveJobResponse)
	err := c.cc.Invoke(ctx, "/inflion.inflionserver.job.v1.JobInfo/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobInfoServer is the server API for JobInfo service.
type JobInfoServer interface {
	List(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	Create(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	Remove(context.Context, *RemoveJobRequest) (*RemoveJobResponse, error)
}

// UnimplementedJobInfoServer can be embedded to have forward compatible implementations.
type UnimplementedJobInfoServer struct {
}

func (*UnimplementedJobInfoServer) List(ctx context.Context, req *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedJobInfoServer) Create(ctx context.Context, req *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedJobInfoServer) Remove(ctx context.Context, req *RemoveJobRequest) (*RemoveJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterJobInfoServer(s *grpc.Server, srv JobInfoServer) {
	s.RegisterService(&_JobInfo_serviceDesc, srv)
}

func _JobInfo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobInfoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.job.v1.JobInfo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobInfoServer).List(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.job.v1.JobInfo/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobInfoServer).Create(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobInfo_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobInfoServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inflion.inflionserver.job.v1.JobInfo/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobInfoServer).Remove(ctx, req.(*RemoveJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inflion.inflionserver.job.v1.JobInfo",
	HandlerType: (*JobInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _JobInfo_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _JobInfo_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _JobInfo_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
