/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	appsv1 "github.com/inflion/api/apps/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFlows implements FlowInterface
type FakeFlows struct {
	Fake *FakeAppsV1
	ns   string
}

var flowsResource = schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "flows"}

var flowsKind = schema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "Flow"}

// Get takes name of the flow, and returns the corresponding flow object, and an error if there is any.
func (c *FakeFlows) Get(ctx context.Context, name string, options v1.GetOptions) (result *appsv1.Flow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(flowsResource, c.ns, name), &appsv1.Flow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Flow), err
}

// List takes label and field selectors, and returns the list of Flows that match those selectors.
func (c *FakeFlows) List(ctx context.Context, opts v1.ListOptions) (result *appsv1.FlowList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(flowsResource, flowsKind, c.ns, opts), &appsv1.FlowList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appsv1.FlowList{ListMeta: obj.(*appsv1.FlowList).ListMeta}
	for _, item := range obj.(*appsv1.FlowList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested flows.
func (c *FakeFlows) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(flowsResource, c.ns, opts))

}

// Create takes the representation of a flow and creates it.  Returns the server's representation of the flow, and an error, if there is any.
func (c *FakeFlows) Create(ctx context.Context, flow *appsv1.Flow, opts v1.CreateOptions) (result *appsv1.Flow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(flowsResource, c.ns, flow), &appsv1.Flow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Flow), err
}

// Update takes the representation of a flow and updates it. Returns the server's representation of the flow, and an error, if there is any.
func (c *FakeFlows) Update(ctx context.Context, flow *appsv1.Flow, opts v1.UpdateOptions) (result *appsv1.Flow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(flowsResource, c.ns, flow), &appsv1.Flow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Flow), err
}

// Delete takes name of the flow and deletes it. Returns an error if one occurs.
func (c *FakeFlows) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(flowsResource, c.ns, name), &appsv1.Flow{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFlows) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(flowsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &appsv1.FlowList{})
	return err
}

// Patch applies the patch and returns the patched flow.
func (c *FakeFlows) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appsv1.Flow, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(flowsResource, c.ns, name, pt, data, subresources...), &appsv1.Flow{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Flow), err
}
