// Code generated by sqlc. DO NOT EDIT.
// source: matcher_rule.sql

package store

import (
	"context"
)

const getMatcherRules = `-- name: GetRules :many
SELECT id, project_id, rule_name, target_flow_name, rules, created_at, updated_at
FROM matcher_rule
WHERE
    project_id = $1
`

func (q *Queries) GetMatcherRules(ctx context.Context, projectID int64) ([]MatcherRule, error) {
	rows, err := q.query(ctx, q.getMatcherRulesStmt, getMatcherRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatcherRule
	for rows.Next() {
		var i MatcherRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RuleName,
			&i.TargetFlowName,
			&i.Rules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
