// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Action struct {
	ID        int64
	UserID    string
	ProjectID int64
	Name      string
	Body      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AwsAccount struct {
	ID         int64
	UserID     string
	ProjectID  int64
	AccountID  string
	RoleName   string
	ExternalID string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Instance struct {
	ID         int64
	Name       string
	InstanceID string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ProjectID  int64
}

type InstanceAtService struct {
	ID         int64
	ServiceID  int64
	InstanceID int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type NotificationRule struct {
	ID        int64
	ProjectID int64
	RuleName  string
	Rules     json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Organization struct {
	ID         int64
	Name       string
	UniqueName string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Project struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      string
}

type ProjectCollaborator struct {
	UserID    string
	ProjectID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProjectInOrganization struct {
	ProjectID      int64
	OrganizationID int64
}

type ProjectInvitation struct {
	ID            int64
	InviteeUserID string
	ProjectID     int64
	MailAddress   string
	Token         string
	Confirmed     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type SecurityGroup struct {
	ID                int64
	SecurityGroupID   string
	SecurityGroupName string
}

type Service struct {
	ID        int64
	ProjectID int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SlackWebhook struct {
	ID         int64
	UserID     string
	ProjectID  int64
	Name       string
	Channel    string
	WebhookUrl string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type UserAccount struct {
	ID        string
	Username  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
