// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"context"
)

type Querier interface {
	AddToProject(ctx context.Context, arg AddToProjectParams) (ProjectCollaborator, error)
	AllAwsAccount(ctx context.Context) ([]AllAwsAccountRow, error)
	ConfirmInvitation(ctx context.Context, token string) (ProjectInvitation, error)
	CountProjectCollaboratorByUserId(ctx context.Context, arg CountProjectCollaboratorByUserIdParams) (int64, error)
	CreateSecurityGroup(ctx context.Context, arg CreateSecurityGroupParams) error
	GetActions(ctx context.Context, projectID int64) ([]Action, error)
	GetAwsAccount(ctx context.Context, projectID int64) (GetAwsAccountRow, error)
	GetInvitationByToken(ctx context.Context, token string) (ProjectInvitation, error)
	GetNotificationRules(ctx context.Context, projectID int64) ([]NotificationRule, error)
	GetSlackWebHooks(ctx context.Context, projectID int64) ([]SlackWebhook, error)
	LinkInstanceWithService(ctx context.Context, arg LinkInstanceWithServiceParams) (InstanceAtService, error)
	ResolveIdByInstanceId(ctx context.Context, instanceID string) (int64, error)
	SelectInstance(ctx context.Context) ([]Instance, error)
	UpsertInstance(ctx context.Context, arg UpsertInstanceParams) (Instance, error)
	UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
