// Code generated by sqlc. DO NOT EDIT.
// source: slack_webhook.sql

package store

import (
	"context"
)

const getSlackWebHooks = `-- name: GetSlackWebHooks :many
SELECT id, user_id, project_id, name, channel, webhook_url, created_at, updated_at
FROM slack_webhook
WHERE project_id = $1
`

func (q *Queries) GetSlackWebHooks(ctx context.Context, projectID int64) ([]SlackWebhook, error) {
	rows, err := q.query(ctx, q.getSlackWebHooksStmt, getSlackWebHooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlackWebhook
	for rows.Next() {
		var i SlackWebhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Name,
			&i.Channel,
			&i.WebhookUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
