// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package ops

import (
	"github.com/inflion/inflion/internal/ops/monitor"
	"github.com/inflion/inflion/internal/ops/notification"
	"github.com/inflion/inflion/internal/ops/producer"
	"github.com/inflion/inflion/internal/ops/syncer"
	"github.com/inflion/inflion/internal/store"
	"github.com/inflion/inflion/internal/timescale"
)

// Injectors from wire.go:

func Initialize() (Ops, error) {
	dbtx, err := store.NewDbtx()
	if err != nil {
		return Ops{}, err
	}
	queries := store.New(dbtx)
	timescaleDBTX, err := timescale.NewDbtx()
	if err != nil {
		return Ops{}, err
	}
	timescaleQueries := timescale.New(timescaleDBTX)
	producerProducer := producer.NewProducer()
	monitorMonitor := monitor.NewMonitor(queries, timescaleQueries, producerProducer)
	broker := notification.NewBroker(queries)
	syncerSyncer := syncer.NewSyncer(queries)
	ops := newOps(monitorMonitor, broker, syncerSyncer)
	return ops, nil
}
