// Code generated by sqlc. DO NOT EDIT.

package timescale

import (
	"database/sql"
	"time"
)

type Metric struct {
	Time       time.Time
	InstanceID string
	Type       string
	Value      sql.NullFloat64
}
